framework:
  messenger:
    transports:
      sync: 'sync://'

    routing:
      App\Message\InformAuctioneerMessage: sync

when@test:
  framework:
    messenger:
      transports:
        sync: 'in-memory://'
